import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <nav className="bg-white shadow p-4">
          <div className="flex gap-4">
            <Link href="/" className="text-blue-600 hover:underline">
              Home
            </Link>
            <Link href="/about" className="text-blue-600 hover:underline">
              About
            </Link>
            <Link href="/notes" className="text-blue-600 hover:underline">
              Notes
            </Link>
            <Link href="/chat" className="text-blue-600 hover:underline">
              Chat
            </Link>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
